// assets/DevExtreme/Demos/WidgetsGallery/Demos/TreeList/RowEditing/React/App.js
import React from 'react';
import { TreeList, Editing, Column, RequiredRule, Lookup } from 'devextreme-react/tree-list';
import { employees } from './data.js';

const expandedRowKeys = [1, 2, 3, 4, 5];

const headDataSource = {
  store: employees,
  sort: 'Full_Name'
};

class App extends React.Component {
  render() {
    return (
      <div id="tree-list-demo">
        <TreeList
          id="employees"
          dataSource={employees}
          showRowLines={true}
          showBorders={true}
          columnAutoWidth={true}
          defaultExpandedRowKeys={expandedRowKeys}
          keyExpr="ID"
          parentIdExpr="Head_ID"
          onCellPrepared={this.onCellPrepared}
          onEditorPreparing={this.onEditorPreparing}
          onInitNewRow={this.onInitNewRow}
        >
          <Editing
            allowUpdating={true}
            allowDeleting={true}
            allowAdding={true}
            mode="row" />
          <Column
            dataField="Full_Name">
            <RequiredRule />
          </Column>
          <Column
            dataField="Head_ID"
            caption="Head">
            <Lookup
              dataSource={headDataSource}
              valueExpr="ID"
              displayExpr="Full_Name" />
            <RequiredRule />
          </Column>
          <Column
            dataField="Title"
            caption="Position">
            <RequiredRule />
          </Column>
          <Column
            width={120}
            dataField="Hire_Date"
            dataType="date">
            <RequiredRule />
          </Column>
        </TreeList>
      </div>
    );
  }
  onCellPrepared(e) {
    if(e.column.command === 'edit') {
      let addLink = e.cellElement.querySelector('.dx-link-add');

      if(addLink) {
        addLink.remove();
      }
    }
  }
  onEditorPreparing(e) {
    if(e.dataField === 'Head_ID' && e.row.data.ID === 1) {
      e.cancel = true;
    }
  }
  onInitNewRow(e) {
    e.data.Head_ID = 1;
  }
}

export default App;

// assets/DevExtreme/Demos/WidgetsGallery/Demos/TreeList/RowEditing/Angular/app/app.component.ts
import { NgModule, Component, enableProdMode } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { DxTreeListModule } from 'devextreme-angular';

import { Employee, Service } from './app.service';

if(!/localhost/.test(document.location.host)) {
    enableProdMode();
}

@Component({
    selector: 'demo-app',
    templateUrl: 'app/app.component.html',
    styleUrls: ['app/app.component.css'],
    providers: [Service]
})
export class AppComponent {
    employees: Employee[];
    lookupData: any;

    constructor(service: Service) {
        this.employees = service.getEmployees();

        this.lookupData = {
            store: {
                type: "array",
                data: this.employees,
                sort: "Full_Name"
            }

        };
    }
    
    cellPrepared(e) {
        if(e.column.command === "edit") {
            let addLink = e.cellElement.querySelector(".dx-link-add");
            
            if(addLink) {
               addLink.remove();
            }
        }
    }

    editorPreparing(e) {
        if(e.dataField === "Head_ID" && e.row.data.ID === 1) {
            e.cancel = true;
        }
    }

    initNewRow(e) {
        e.data.Head_ID = 1;
    }
}

@NgModule({
    imports: [
        BrowserModule,
        DxTreeListModule
    ],
    declarations: [AppComponent],
    bootstrap: [AppComponent]
})
export class AppModule { }

platformBrowserDynamic().bootstrapModule(AppModule);
<div id="tree-list-demo">
    <dx-tree-list
        id="employees"
        [dataSource]="employees"
        keyExpr="ID"
        parentIdExpr="Head_ID"
        [showRowLines]="true"
        [showBorders]="true"
        [columnAutoWidth]="true"
        [expandedRowKeys]="[1, 2, 3, 4, 5]"
        (onEditorPreparing)="editorPreparing($event)"
        (onInitNewRow)="initNewRow($event)"
        (onCellPrepared)="cellPrepared($event)">
        <dxo-editing
            mode="row"
            [allowUpdating]="true"
            [allowDeleting]="true"
            [allowAdding]="true">
        </dxo-editing>

        <dxi-column dataField="Full_Name">
            <dxi-validation-rule type="required"></dxi-validation-rule>
        </dxi-column>
        <dxi-column dataField="Head_ID" caption="Head">
            <dxo-lookup
                [dataSource]="lookupData"
                valueExpr="ID"
                displayExpr="Full_Name">
            </dxo-lookup>
            <dxi-validation-rule type="required"></dxi-validation-rule>
        </dxi-column>
        <dxi-column dataField="Title" caption="Position">
            <dxi-validation-rule type="required"></dxi-validation-rule>
        </dxi-column>
        <dxi-column dataField="Hire_Date" dataType="date" [width]="120">
            <dxi-validation-rule type="required"></dxi-validation-rule>
        </dxi-column>
    </dx-tree-list>
</div>
