// assets/DevExtreme/Demos/WidgetsGallery/Demos/TreeList/PopupEditing/Angular/app/app.component.ts
import { NgModule, Component, enableProdMode } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { DxTreeListModule } from 'devextreme-angular';

import { Employee, Service } from './app.service';

if(!/localhost/.test(document.location.host)) {
    enableProdMode();
}

@Component({
    selector: 'demo-app',
    templateUrl: 'app/app.component.html',
    styleUrls: ['app/app.component.css'],
    providers: [Service]
})
export class AppComponent {
    employees: Employee[];
    lookupData: any;
    
    constructor(service: Service) {
        this.employees = service.getEmployees();
        this.lookupData = {
            store: {
                type: "array",
                data: this.employees,
                group: "City"
            }

        };
    }

    cellPrepared(e) {
        if(e.column.command === "edit") {
            let addLink = e.cellElement.querySelector(".dx-link-add");
            
            if(addLink) {
               addLink.remove();
            }
        }
    }

    editorPreparing(e) {
        if(e.dataField === "Head_ID" && e.row.data.ID === 1) {
            e.editorOptions.disabled = true;
            e.editorOptions.value = null;
        }
    }

    initNewRow(e) {
        e.data.Head_ID = 1;
    }
}

@NgModule({
    imports: [
        BrowserModule,
        DxTreeListModule
    ],
    declarations: [AppComponent],
    bootstrap: [AppComponent]
})
export class AppModule { }

platformBrowserDynamic().bootstrapModule(AppModule);
<div id="tree-list-demo">
    <dx-tree-list
        id="employees"
        [dataSource]="employees"
        keyExpr="ID"
        parentIdExpr="Head_ID"
        [showRowLines]="true"
        [showBorders]="true"
        [columnAutoWidth]="true"
        [expandedRowKeys]="[1]"
        (onEditorPreparing)="editorPreparing($event)"
        (onInitNewRow)="initNewRow($event)"
        (onCellPrepared)="cellPrepared($event)">
        <dxo-editing
            mode="popup"
            [allowUpdating]="true"
            [allowDeleting]="true"
            [allowAdding]="true">
            <dxo-popup
                title="Employee Info"
                [showTitle]="true"
                [width]="700"
                [position] = "{ my: 'top', at: 'top', of: window }">
            </dxo-popup>
        </dxo-editing>

        <dxi-column dataField="Full_Name">
            <dxi-validation-rule type="required"></dxi-validation-rule>
        </dxi-column>
        <dxi-column dataField="Prefix" caption="Title">
            <dxi-validation-rule type="required"></dxi-validation-rule>
        </dxi-column>
        <dxi-column dataField="Head_ID" caption="Head" [visible]="false">
            <dxo-lookup
                [dataSource]="lookupData"
                valueExpr="ID"
                displayExpr="Full_Name">
            </dxo-lookup>
            <dxi-validation-rule type="required"></dxi-validation-rule>
        </dxi-column>
        <dxi-column dataField="Title" caption="Position">
            <dxi-validation-rule type="required"></dxi-validation-rule>
        </dxi-column>
        <dxi-column dataField="City" [width]="150">
            <dxi-validation-rule type="required"></dxi-validation-rule>
        </dxi-column>
        <dxi-column dataField="Hire_Date" dataType="date" [width]="120">
            <dxi-validation-rule type="required"></dxi-validation-rule>
        </dxi-column>
    </dx-tree-list>
</div>

// assets/DevExtreme/Demos/WidgetsGallery/Demos/TreeList/PopupEditing/React/App.js
import React from 'react';
import { TreeList, Editing, Column, ValidationRule, Lookup } from 'devextreme-react/tree-list';
import { employees } from './data.js';

const expandedRowKeys = [1];

const popupOptions = {
  title: 'Employee Info',
  showTitle: true,
  width: 700,
  position: { my: 'top', at: 'top', of: window }
};

const lookupData = {
  store: employees,
  sort: 'Full_Name'
};

class App extends React.Component {
  render() {
    return (
      <div id="tree-list-demo">
        <TreeList
          dataSource={employees}
          columnAutoWidth={true}
          showRowLines={true}
          showBorders={true}
          defaultExpandedRowKeys={expandedRowKeys}
          keyExpr="ID"
          parentIdExpr="Head_ID"
          onCellPrepared={this.onCellPrepared}
          onEditorPreparing={this.onEditorPreparing}
          onInitNewRow={this.onInitNewRow}
        >
          <Editing allowUpdating={true} allowDeleting={true} allowAdding={true} popup={popupOptions} mode="popup" />
          <Column dataField="Full_Name">
            <ValidationRule type="required" />
          </Column>
          <Column dataField="Prefix" caption="Title">
            <ValidationRule type="required" />
          </Column>
          <Column visible={false} dataField="Head_ID" caption="Head">
            <Lookup dataSource={lookupData} valueExpr="ID" displayExpr="Full_Name" />
            <ValidationRule type="required" />
          </Column>
          <Column dataField="Title" caption="Position">
            <ValidationRule type="required" />
          </Column>
          <Column width={150} dataField="City">
            <ValidationRule type="required" />
          </Column>
          <Column width={120} dataField="Hire_Date" dataType="date">
            <ValidationRule type="required" />
          </Column>
        </TreeList>
      </div>
    );
  }

  onCellPrepared(e) {
    if(e.column.command === 'edit') {
      let addLink = e.cellElement.querySelector('.dx-link-add');

      if(addLink) {
        addLink.remove();
      }
    }
  }
  onEditorPreparing(e) {
    if (e.dataField === 'Head_ID' && e.row.data.ID === 1) {
      e.editorOptions.disabled = true;
      e.editorOptions.value = null;
    }
  }
  onInitNewRow(e) {
    e.data.Head_ID = 1;
  }
}

export default App;
